"""user_token table

Revision ID: b3d28c655aef
Revises: 4e542e739f63
Create Date: 2023-12-16 00:47:35.955809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d28c655aef'
down_revision: Union[str, None] = '4e542e739f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=250), nullable=True),
    sa.Column('refresh_token', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token_access_token'), 'user_token', ['access_token'], unique=False)
    op.create_index(op.f('ix_user_token_refresh_token'), 'user_token', ['refresh_token'], unique=False)
    op.add_column('user', sa.Column('username', sa.String(length=150), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('user', 'username')
    op.drop_index(op.f('ix_user_token_refresh_token'), table_name='user_token')
    op.drop_index(op.f('ix_user_token_access_token'), table_name='user_token')
    op.drop_table('user_token')
    # ### end Alembic commands ###
